

import java.awt.Color;
import clases.Servicios;
import clases.*;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tenshi Wings
 */
public class GestionMaterial extends javax.swing.JFrame {
  Servicios serv = new Servicios();
  ResultSet resultSet;
  PreparedStatement preparedStatement;
  /**
   * Creates new form GestionMaterial
   */
  public GestionMaterial() {
    initComponents();
    inhabilitarEtiquetas();
  }

  
  public void inhabilitarEtiquetas(){
    this.txtBusqueda.setText("Búsqueda");
    this.txtBusqueda.setForeground(Color.GRAY);  
    this.txtTitulo.setEditable(false);this.txtAutor.setEditable(false);
    this.txtEditorial.setEditable(false);
    this.txtEdicion.setEditable(false);
    this.cbTipoMaterial.setEditable(false);
    this.btnBuscar.setEnabled(false);
    this.panelBusqueda.setBackground(Color.DARK_GRAY);
    this.etqEditaMaterial.setForeground(Color.DARK_GRAY);
    this.etqNuevoMaterial.setForeground(Color.DARK_GRAY);
    this.etqBusqueda.setForeground(Color.WHITE);
    this.cbTipoMaterial.setEnabled(false);
    this.txtTitulo.setText("");
    this.txtAutor.setText("");
    this.txtEditorial.setText("");
    this.txtEdicion.setText("");
    this.cbTipoMaterial.setSelectedIndex(0);
  }

  /**
   *Funcion para Inhabilitar Etiquetas
   */
  public void habilitarEtiquetas(){
    this.txtBusqueda.setEditable(true);
    this.txtTitulo.setEditable(true);
    this.txtAutor.setEditable(true);
    this.txtEditorial.setEditable(true);
    this.txtEdicion.setEditable(true);
    this.cbTipoMaterial.setEditable(true);
    this.cbTipoMaterial.setEnabled(true);
    this.cbTipoMaterial.setEditable(false);
    this.txtTitulo.setText("");
    this.txtAutor.setText("");
    this.txtEditorial.setText("");
    this.txtEdicion.setText("");
    this.cbTipoMaterial.setSelectedIndex(0);
 
  }
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jTabbedPane3 = new javax.swing.JTabbedPane();
    jPanel6 = new javax.swing.JPanel();
    btnGuardar = new javax.swing.JButton();
    EtqIdMaterial = new javax.swing.JLabel();
    txtTitulo = new javax.swing.JTextField();
    txtEdicion = new javax.swing.JTextField();
    jLabel9 = new javax.swing.JLabel();
    etqEdicion = new javax.swing.JLabel();
    etqAutor = new javax.swing.JLabel();
    etqFechaPublicacion = new javax.swing.JLabel();
    etqTipoMaterial = new javax.swing.JLabel();
    cbTipoMaterial = new javax.swing.JComboBox();
    btnBaja = new javax.swing.JButton();
    panelBusqueda = new javax.swing.JPanel();
    etqNuevoMaterial = new javax.swing.JLabel();
    etqEditaMaterial = new javax.swing.JLabel();
    etqBusqueda = new javax.swing.JLabel();
    txtBusqueda = new javax.swing.JTextField();
    btnBuscar = new javax.swing.JButton();
    btnCancelar = new javax.swing.JButton();
    etqTitulo = new javax.swing.JLabel();
    txtAutor = new javax.swing.JTextField();
    txtFechaPublicacion = new javax.swing.JTextField();
    etqEditorial = new javax.swing.JLabel();
    txtEditorial = new javax.swing.JTextField();
    jPanel2 = new javax.swing.JPanel();
    jPanel8 = new javax.swing.JPanel();
    etq2Matricula4 = new javax.swing.JLabel();
    jPanel23 = new javax.swing.JPanel();
    jScrollPane2 = new javax.swing.JScrollPane();
    TablaHistorialPrestamos = new javax.swing.JTable();
    jComboBox1 = new javax.swing.JComboBox<String>();
    jPanel3 = new javax.swing.JPanel();
    jPanel9 = new javax.swing.JPanel();
    jPanel24 = new javax.swing.JPanel();
    jScrollPane3 = new javax.swing.JScrollPane();
    TablaAdeudos = new javax.swing.JTable();
    jLabel1 = new javax.swing.JLabel();
    jTextField1 = new javax.swing.JTextField();
    jButton1 = new javax.swing.JButton();
    jPanel20 = new javax.swing.JPanel();
    jLabel8 = new javax.swing.JLabel();
    jPanel17 = new javax.swing.JPanel();
    jPanel18 = new javax.swing.JPanel();
    jPanel19 = new javax.swing.JPanel();
    etqAyuda = new javax.swing.JLabel();
    jLabel24 = new javax.swing.JLabel();
    jLabel30 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    etqVolver = new javax.swing.JLabel();
    etqSalir = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jTabbedPane3.setBackground(new java.awt.Color(204, 204, 255));
    jTabbedPane3.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
    jTabbedPane3.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

    jPanel6.setBackground(new java.awt.Color(255, 255, 255));

    btnGuardar.setBackground(new java.awt.Color(204, 204, 204));
    btnGuardar.setText("Guardar material");
    btnGuardar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnGuardarActionPerformed(evt);
      }
    });
    btnGuardar.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        btnGuardarKeyPressed(evt);
      }
    });

    EtqIdMaterial.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
    EtqIdMaterial.setText("Folio");

    jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/uv.jpg"))); // NOI18N
    jLabel9.setText("jLabel8");

    etqEdicion.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
    etqEdicion.setText("Edicion");

    etqAutor.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
    etqAutor.setText("Autor");

    etqFechaPublicacion.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
    etqFechaPublicacion.setText("Fecha de publicación");

    etqTipoMaterial.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
    etqTipoMaterial.setText("Tipo de material");

    cbTipoMaterial.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Libro", "Revista", "Periódico", "Mapa", "Medios ópticos", "Software" }));
    cbTipoMaterial.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cbTipoMaterialActionPerformed(evt);
      }
    });

    btnBaja.setBackground(new java.awt.Color(204, 204, 204));
    btnBaja.setText("Dar de baja");
    btnBaja.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnBajaActionPerformed(evt);
      }
    });

    panelBusqueda.setBackground(new java.awt.Color(153, 153, 153));

    etqNuevoMaterial.setFont(new java.awt.Font("Microsoft JhengHei", 0, 16)); // NOI18N
    etqNuevoMaterial.setText("Nuevo material");

    etqEditaMaterial.setFont(new java.awt.Font("Microsoft JhengHei", 0, 16)); // NOI18N
    etqEditaMaterial.setText("Editar material");

    etqBusqueda.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
    etqBusqueda.setText("Búsqueda");

    javax.swing.GroupLayout panelBusquedaLayout = new javax.swing.GroupLayout(panelBusqueda);
    panelBusqueda.setLayout(panelBusquedaLayout);
    panelBusquedaLayout.setHorizontalGroup(
      panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelBusquedaLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(etqNuevoMaterial)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(etqBusqueda)
        .addGap(249, 249, 249)
        .addComponent(etqEditaMaterial)
        .addGap(70, 70, 70))
    );
    panelBusquedaLayout.setVerticalGroup(
      panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBusquedaLayout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addGroup(panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(etqNuevoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(etqEditaMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(etqBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
    );

    txtBusqueda.setForeground(new java.awt.Color(204, 204, 204));
    txtBusqueda.setText("Búsqueda");
    txtBusqueda.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
      public void mouseDragged(java.awt.event.MouseEvent evt) {
        txtBusquedaMouseDragged(evt);
      }
    });
    txtBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        txtBusquedaMouseClicked(evt);
      }
    });
    txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtBusquedaActionPerformed(evt);
      }
    });
    txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        txtBusquedaKeyPressed(evt);
      }
    });

    btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
    btnBuscar.setText("Buscar");
    btnBuscar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnBuscarActionPerformed(evt);
      }
    });
    btnBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        btnBuscarKeyPressed(evt);
      }
    });

    btnCancelar.setBackground(new java.awt.Color(204, 204, 204));
    btnCancelar.setText("Cancelar");
    btnCancelar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCancelarActionPerformed(evt);
      }
    });
    btnCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        btnCancelarKeyPressed(evt);
      }
    });

    etqTitulo.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
    etqTitulo.setText("Titulo");

    txtAutor.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtAutorActionPerformed(evt);
      }
    });

    etqEditorial.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
    etqEditorial.setText("Editorial");

    txtEditorial.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtEditorialActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
    jPanel6.setLayout(jPanel6Layout);
    jPanel6Layout.setHorizontalGroup(
      jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panelBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(jPanel6Layout.createSequentialGroup()
        .addGap(85, 85, 85)
        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(jPanel6Layout.createSequentialGroup()
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(EtqIdMaterial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar)
                .addGap(197, 197, 197))
              .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(etqAutor)
                .addGap(465, 465, 465)
                .addComponent(txtEditorial))
              .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(etqTitulo)
                .addGap(34, 34, 34)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(txtAutor)
                  .addComponent(txtTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel6Layout.createSequentialGroup()
                    .addComponent(etqEdicion)
                    .addGap(43, 43, 43)
                    .addComponent(txtEdicion))
                  .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(etqEditorial)
                      .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(etqFechaPublicacion)
                        .addGap(18, 18, 18)
                        .addComponent(txtFechaPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))))
            .addGap(113, 113, 113))
          .addGroup(jPanel6Layout.createSequentialGroup()
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(233, 233, 233)
                .addComponent(btnGuardar)
                .addGap(160, 160, 160)
                .addComponent(btnBaja)
                .addGap(63, 63, 63))
              .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(etqTipoMaterial)
                .addGap(18, 18, 18)
                .addComponent(cbTipoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
    );
    jPanel6Layout.setVerticalGroup(
      jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel6Layout.createSequentialGroup()
        .addComponent(panelBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(jPanel6Layout.createSequentialGroup()
            .addGap(33, 188, Short.MAX_VALUE)
            .addComponent(jLabel9))
          .addGroup(jPanel6Layout.createSequentialGroup()
            .addGap(38, 38, 38)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(EtqIdMaterial)
              .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(btnBuscar))
            .addGap(18, 18, 18)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(etqEditorial))
              .addComponent(etqTitulo))
            .addGap(25, 25, 25)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(etqAutor)
              .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(txtEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(etqEdicion))
            .addGap(32, 32, 32)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(etqTipoMaterial)
              .addComponent(cbTipoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(etqFechaPublicacion)
              .addComponent(txtFechaPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(97, 97, 97)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(btnCancelar)
              .addComponent(btnGuardar)
              .addComponent(btnBaja))
            .addContainerGap(22, Short.MAX_VALUE))))
    );

    jTabbedPane3.addTab("Buscar material", jPanel6);

    jPanel8.setBackground(new java.awt.Color(255, 255, 255));

    etq2Matricula4.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
    etq2Matricula4.setText("Búsqueda por:");

    jPanel23.setBackground(new java.awt.Color(0, 153, 0));

    javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
    jPanel23.setLayout(jPanel23Layout);
    jPanel23Layout.setHorizontalGroup(
      jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );
    jPanel23Layout.setVerticalGroup(
      jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 20, Short.MAX_VALUE)
    );

    TablaHistorialPrestamos.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null}
      },
      new String [] {
        "Título", "Autor", "Tipo de material", "Fecha de préstamo", "Fecha devolución", "Estado", "Extender"
      }
    ));
    jScrollPane2.setViewportView(TablaHistorialPrestamos);

    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    jComboBox1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jComboBox1ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
    jPanel8.setLayout(jPanel8Layout);
    jPanel8Layout.setHorizontalGroup(
      jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel8Layout.createSequentialGroup()
        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(jPanel8Layout.createSequentialGroup()
            .addGap(111, 111, 111)
            .addComponent(etq2Matricula4)
            .addGap(39, 39, 39)
            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
        .addGap(0, 34, Short.MAX_VALUE)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 904, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(25, 25, 25))
    );
    jPanel8Layout.setVerticalGroup(
      jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel8Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(etq2Matricula4)
          .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(27, 27, 27)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(256, 256, 256))
    );

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 963, Short.MAX_VALUE)
      .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
          .addGap(0, 0, Short.MAX_VALUE)
          .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(0, 0, Short.MAX_VALUE)))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 563, Short.MAX_VALUE)
      .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
          .addGap(0, 0, Short.MAX_VALUE)
          .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(0, 0, Short.MAX_VALUE)))
    );

    jTabbedPane3.addTab("Ver historial de préstamos", jPanel2);

    jPanel9.setBackground(new java.awt.Color(255, 255, 255));

    jPanel24.setBackground(new java.awt.Color(0, 153, 0));

    javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
    jPanel24.setLayout(jPanel24Layout);
    jPanel24Layout.setHorizontalGroup(
      jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 951, Short.MAX_VALUE)
    );
    jPanel24Layout.setVerticalGroup(
      jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 20, Short.MAX_VALUE)
    );

    TablaAdeudos.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null, null, null},
        {null, null, null, null, null, null},
        {null, null, null, null, null, null},
        {null, null, null, null, null, null},
        {null, null, null, null, null, null},
        {null, null, null, null, null, null},
        {null, null, null, null, null, null},
        {null, null, null, null, null, null},
        {null, null, null, null, null, null},
        {null, null, null, null, null, null},
        {null, null, null, null, null, null},
        {null, null, null, null, null, null},
        {null, null, null, null, null, null},
        {null, null, null, null, null, null},
        {null, null, null, null, null, null}
      },
      new String [] {
        "Título", "Autor", "Tipo de material", "Días de atraso", "Monto", "Estado"
      }
    ));
    jScrollPane3.setViewportView(TablaAdeudos);

    jLabel1.setText("Total");

    jTextField1.setText("$0");
    jTextField1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextField1ActionPerformed(evt);
      }
    });

    jButton1.setText("Registrar pago de adeudo");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
    jPanel9.setLayout(jPanel9Layout);
    jPanel9Layout.setHorizontalGroup(
      jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel9Layout.createSequentialGroup()
        .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 898, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(31, 31, 31))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addGap(35, 35, 35)
            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(232, 232, 232))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
            .addComponent(jButton1)
            .addGap(368, 368, 368))))
    );
    jPanel9Layout.setVerticalGroup(
      jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel9Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(jButton1)
        .addGap(248, 248, 248))
    );

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 963, Short.MAX_VALUE)
      .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
          .addGap(0, 0, Short.MAX_VALUE)
          .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(0, 0, Short.MAX_VALUE)))
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 569, Short.MAX_VALUE)
      .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
          .addGap(0, 0, Short.MAX_VALUE)
          .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(0, 0, Short.MAX_VALUE)))
    );

    jTabbedPane3.addTab("Ver adeudos", jPanel3);

    jPanel20.setBackground(new java.awt.Color(51, 51, 51));

    jLabel8.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
    jLabel8.setForeground(new java.awt.Color(255, 255, 255));
    jLabel8.setText("Universidad Veracruzana");

    javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
    jPanel20.setLayout(jPanel20Layout);
    jPanel20Layout.setHorizontalGroup(
      jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jLabel8)
        .addContainerGap())
    );
    jPanel20Layout.setVerticalGroup(
      jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    jPanel17.setBackground(new java.awt.Color(153, 153, 153));

    jPanel18.setBackground(new java.awt.Color(51, 51, 51));

    jPanel19.setBackground(new java.awt.Color(51, 102, 255));

    etqAyuda.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
    etqAyuda.setForeground(new java.awt.Color(255, 255, 255));
    etqAyuda.setText("Ayuda");
    etqAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        etqAyudaMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
    jPanel19.setLayout(jPanel19Layout);
    jPanel19Layout.setHorizontalGroup(
      jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(etqAyuda)
        .addContainerGap())
    );
    jPanel19Layout.setVerticalGroup(
      jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(etqAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    jLabel24.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N
    jLabel24.setForeground(new java.awt.Color(255, 255, 255));
    jLabel24.setText("Gestión de material");

    javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
    jPanel18.setLayout(jPanel18Layout);
    jPanel18Layout.setHorizontalGroup(
      jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(jPanel18Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel24)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel18Layout.setVerticalGroup(
      jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
        .addContainerGap(19, Short.MAX_VALUE)
        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo.png"))); // NOI18N
    jLabel30.setText("jLabel6");

    jLabel7.setFont(new java.awt.Font("Microsoft JhengHei", 0, 24)); // NOI18N
    jLabel7.setForeground(new java.awt.Color(255, 255, 255));
    jLabel7.setText("Biblioteca UV");

    etqVolver.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
    etqVolver.setForeground(new java.awt.Color(255, 255, 255));
    etqVolver.setText("Volver");
    etqVolver.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        etqVolverMouseClicked(evt);
      }
    });

    etqSalir.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
    etqSalir.setForeground(new java.awt.Color(255, 255, 255));
    etqSalir.setText("Salir");
    etqSalir.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        etqSalirMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
    jPanel17.setLayout(jPanel17Layout);
    jPanel17Layout.setHorizontalGroup(
      jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(jPanel17Layout.createSequentialGroup()
        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
        .addComponent(etqVolver)
        .addGap(18, 18, 18)
        .addComponent(etqSalir)
        .addContainerGap())
    );
    jPanel17Layout.setVerticalGroup(
      jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(jPanel17Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel7)
              .addComponent(etqVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(etqSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGroup(jPanel17Layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(jPanel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(layout.createSequentialGroup()
        .addGap(46, 46, 46)
        .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 968, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
        .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  public void actionClickCancelar(){
    inhabilitarEtiquetas();
    }
  
  private void etqAyudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etqAyudaMouseClicked
    JOptionPane.showMessageDialog(null, "No podemos ayudarle en estos momentos");
  }//GEN-LAST:event_etqAyudaMouseClicked

  private void etqVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etqVolverMouseClicked
    this.dispose();
    MenuCirculacion menu = new MenuCirculacion();
    menu.setVisible(true);
  }//GEN-LAST:event_etqVolverMouseClicked

  private void etqSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etqSalirMouseClicked
    IniciarSesion inicio = new IniciarSesion();
    inicio.setVisible(true);
    setVisible(false);
    this.dispose();
  }//GEN-LAST:event_etqSalirMouseClicked

  private void txtEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditorialActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtEditorialActionPerformed

  private void txtAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtAutorActionPerformed

  private void btnCancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCancelarKeyPressed
    if(evt.getKeyCode() == KeyEvent.VK_ENTER){
    actionClickCancelar();
    }
  }//GEN-LAST:event_btnCancelarKeyPressed

  private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
    actionClickCancelar();
  }//GEN-LAST:event_btnCancelarActionPerformed

  private void btnBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnBuscarKeyPressed
    
  }//GEN-LAST:event_btnBuscarKeyPressed

  private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
    actionClickBuscar();
  }//GEN-LAST:event_btnBuscarActionPerformed

  private void txtBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyPressed
    if(evt.getKeyCode() == KeyEvent.VK_ENTER){
    actionClickBuscar();
    }
  }//GEN-LAST:event_txtBusquedaKeyPressed

  private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed
  
  }//GEN-LAST:event_txtBusquedaActionPerformed

  private void txtBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBusquedaMouseClicked
    this.txtBusqueda.setText("");
    this.txtBusqueda.setForeground(Color.BLACK);
    this.btnBuscar.setEnabled(true);
  }//GEN-LAST:event_txtBusquedaMouseClicked

  private void txtBusquedaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBusquedaMouseDragged

  }//GEN-LAST:event_txtBusquedaMouseDragged

  private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed
    
  }//GEN-LAST:event_btnBajaActionPerformed

  private void cbTipoMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoMaterialActionPerformed
    
  }//GEN-LAST:event_cbTipoMaterialActionPerformed

  private void btnGuardarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnGuardarKeyPressed
    if(evt.getKeyCode() == KeyEvent.VK_ENTER){
    actionClickGuardar();
    }
  }//GEN-LAST:event_btnGuardarKeyPressed

  private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
    actionClickGuardar();
  }//GEN-LAST:event_btnGuardarActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
  }//GEN-LAST:event_jButton1ActionPerformed

  private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
    
  }//GEN-LAST:event_jTextField1ActionPerformed

  private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jComboBox1ActionPerformed
  
  public void actionClickBuscar(){
    ArrayList campos = new ArrayList<String>();
    campos.add("*");
      if(serv.confirmarExistencia("material","folio", txtBusqueda.getText())){
        this.etqEditaMaterial.setForeground(Color.WHITE);
        this.etqNuevoMaterial.setForeground(Color.DARK_GRAY);
        this.etqBusqueda.setForeground(Color.DARK_GRAY);
          try {
            PreparedStatement x = serv.consulta("material", campos, "folio",
            this.txtBusqueda.getText());
            ResultSet rs = x.executeQuery();
              try {
               if (rs.next()){
                habilitarEtiquetas();
                this.txtTitulo.setText(rs.getString("titulo"));
                this.txtAutor.setText(rs.getString("autor"));
                this.txtEditorial.setText(rs.getString("editorial"));
                this.txtBusqueda.setText(rs.getString("folio"));
                this.txtEdicion.setText(rs.getString("edicion"));
                this.cbTipoMaterial.setSelectedIndex(rs.getInt("tipo"));
                 }
                 x.close();
             } catch (SQLException ex) {
                 System.out.println("No se puede establecer conexión");
             }
          }catch(java.lang.NullPointerException ex) {
             System.out.println("ArrayList nulo");
         } catch (SQLException ex) {
             System.out.println("No se puede ejecutar el SQL");
         }
        }else{
            habilitarEtiquetas();
            this.etqEditaMaterial.setForeground(Color.DARK_GRAY);
            this.etqNuevoMaterial.setForeground(Color.WHITE);
            this.etqBusqueda.setForeground(Color.DARK_GRAY);
        }        
    }
    
  public void actionClickGuardar(){
    if(!serv.confirmarExistencia("lector", "id", txtBusqueda.getText())){
      Material material = new Material(this.txtBusqueda.getText(),
      this.txtTitulo.getText(), this.txtEdicion.getText(),
      this.txtEditorial.getText(),this.txtAutor.getText(),
      this.txtFechaPublicacion.getText(),this.cbTipoMaterial.getSelectedIndex(), 1);
      material.agregarMaterial();
    }else{
      Material material = new Material(this.txtBusqueda.getText(),
      this.txtTitulo.getText(), this.txtEdicion.getText(),
      this.txtEditorial.getText(),this.txtAutor.getText(),
      this.txtFechaPublicacion.getText(),this.cbTipoMaterial.getSelectedIndex(), 1);
      material.actualizarMaterial();
    }
      inhabilitarEtiquetas();       
  }
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(GestionMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(GestionMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(GestionMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(GestionMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
        //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new GestionMaterial().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel EtqIdMaterial;
  private javax.swing.JTable TablaAdeudos;
  private javax.swing.JTable TablaHistorialPrestamos;
  private javax.swing.JButton btnBaja;
  private javax.swing.JButton btnBuscar;
  private javax.swing.JButton btnCancelar;
  private javax.swing.JButton btnGuardar;
  private javax.swing.JComboBox cbTipoMaterial;
  private javax.swing.JLabel etq2Matricula4;
  private javax.swing.JLabel etqAutor;
  private javax.swing.JLabel etqAyuda;
  private javax.swing.JLabel etqBusqueda;
  private javax.swing.JLabel etqEdicion;
  private javax.swing.JLabel etqEditaMaterial;
  private javax.swing.JLabel etqEditorial;
  private javax.swing.JLabel etqFechaPublicacion;
  private javax.swing.JLabel etqNuevoMaterial;
  private javax.swing.JLabel etqSalir;
  private javax.swing.JLabel etqTipoMaterial;
  private javax.swing.JLabel etqTitulo;
  private javax.swing.JLabel etqVolver;
  private javax.swing.JButton jButton1;
  private javax.swing.JComboBox<String> jComboBox1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel24;
  private javax.swing.JLabel jLabel30;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel17;
  private javax.swing.JPanel jPanel18;
  private javax.swing.JPanel jPanel19;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel20;
  private javax.swing.JPanel jPanel23;
  private javax.swing.JPanel jPanel24;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel6;
  private javax.swing.JPanel jPanel8;
  private javax.swing.JPanel jPanel9;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JTabbedPane jTabbedPane3;
  private javax.swing.JTextField jTextField1;
  private javax.swing.JPanel panelBusqueda;
  private javax.swing.JTextField txtAutor;
  private javax.swing.JTextField txtBusqueda;
  private javax.swing.JTextField txtEdicion;
  private javax.swing.JTextField txtEditorial;
  private javax.swing.JTextField txtFechaPublicacion;
  private javax.swing.JTextField txtTitulo;
  // End of variables declaration//GEN-END:variables
}
